# Generated by Django 5.0.7 on 2024-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
